CREATE OR REPLACE TRIGGER update_groups_info_trigger
AFTER UPDATE ON STUDENTS
FOR EACH ROW
BEGIN
    UPDATE GROUPS
    SET C_VAL = (SELECT COUNT(*) FROM STUDENTS WHERE GROUP_ID = :NEW.GROUP_ID)
    WHERE ID = :NEW.GROUP_ID;
END;

CREATE OR REPLACE TRIGGER update_students_trigger
AFTER INSERT ON STUDENTS
FOR EACH ROW
BEGIN
    UPDATE GROUPS
    SET C_VAL = (SELECT COUNT(*) FROM STUDENTS WHERE GROUP_ID = :NEW.GROUP_ID)
    WHERE ID = :NEW.GROUP_ID;
END;
