CREATE TABLE LOGS_STUDENTS(
    ID NUMBER PRIMARY KEY,
    ACTION_TYPE VARCHAR(15),
    STUDENT_ID NUMBER,
    ACTION_DATE TIMESTAMP,
    OLD_NAME VARCHAR(50),
    NEW_NAME VARCHAR(50),
    OLD_GROUP_ID NUMBER,
    NEW_GROUP_ID NUMBER
);

CREATE OR REPLACE TRIGGER students_insert_logs
AFTER INSERT ON STUDENTS
FOR EACH ROW
BEGIN
    INSERT INTO LOGS_STUDENTS(ACTION_TYPE, STUDENT_ID, ACTION_DATE, NEW_NAME, NEW_GROUP_ID)
    VALUES ('Insert', :NEW.ID, SYSTIMESTAMP, :NEW.NAME, :NEW.GROUP_ID);
END;

CREATE OR REPLACE TRIGGER students_update_logs
AFTER INSERT ON STUDENTS
FOR EACH ROW
BEGIN
    INSERT INTO LOGS_STUDENTS(ACTION_TYPE, STUDENT_ID, ACTION_DATE,OLD_NAME, NEW_NAME,OLD_GROUP_ID, NEW_GROUP_ID)
    VALUES ('Update', :OLD.ID, SYSTIMESTAMP, :OLD.NAME, :NEW.NAME, :OLD.GROUP_ID, :NEW.GROUP_ID);
END;

CREATE OR REPLACE TRIGGER students_delete_logs
AFTER INSERT ON STUDENTS
FOR EACH ROW
BEGIN
    INSERT INTO LOGS_STUDENTS(ACTION_TYPE, STUDENT_ID, ACTION_DATE,OLD_NAME,OLD_GROUP_ID)
    VALUES ('Delete', :OLD.ID, SYSTIMESTAMP, :OLD.NAME,:OLD.GROUP_ID);
END;